
export const USER_LOGIN_REQUEST = 'USER_CREATE_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_CREATE_ERROR'

export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR'